services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${USERDB}
      POSTGRES_PASSWORD: ${PASSDB}
      POSTGRES_DB: ${APPNAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network: